version: '3.7'

services:
  backend:
    build:
      context: ./  
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=localhost 
      - DB_USER=root
      - DB_PASSWORD=PASS
      - DB_NAME=mydb
    depends_on:
      - db
    # Optional: Use healthcheck to ensure DB is ready before backend starts
    healthcheck:
      test: ["CMD", "mysqlroot", "ping", "-h", "localhost", "-u", "root", "-pPASS"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 20s

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network  

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
