version: '3.7'

services:
  backend:
    build:
      context: ./  # This should be the relative path to the current folder
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database-1.ch2wm0wuekno.ap-northeast-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Abounasar
      - DB_NAME=mydb
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
